// layerfix: prototype of a counter-based (retrograde) in-layer solver.
//
//   layerfix <lhdir> <seeds> <n> [threads] [check=0|1]
//
// Solves layer n from the finished lower layers in <lhdir> and compares the
// result with the stored layer n.  Where solve.cpp iterates
//     gM(b) = max(capM(b), max_noncap gN(child)),  gN(b) = min(capN(b), min_noncap gM(child))
// to a fixpoint by chaotic sweeps (60-90 sweeps per layer, because forced lines
// inside a layer are 80-140 plies long), this solves each threshold t as a
// boolean game with counters, touching every same-layer edge once per
// threshold:
//     W^t = {gM >= t}:  capM >= t, or some non-capturing child in N^t
//     N^t = {gN >= t}:  capN >= t and every non-capturing child in W^t
// A board enters N^t when its counter of non-capturing children not yet in W^t
// drops to zero; its predecessors then enter W^t; their predecessors' counters
// drop; and so on, in generations.  Predecessors are generated by incremental
// un-sowing (O(1) per extra seed).  Thresholds are independent, so the work is
// (V-1) x (edges), which favours the large top layers where V is 3..10.
//
// Memory per board: capM, capN, mcnt, counter (4 bytes), gM/gN result codes
// (2 bytes), W, N and two frontier bitmaps (0.5 byte).
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cinttypes>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <thread>
#include <vector>

#include "layer.hpp"
#include "oware.hpp"

using namespace oware;

static Index IX;
static Layer L[MAX_SEEDS + 1];
static std::string DIR;
static int THREADS = 32;

static const Layer& lh(int n) {
  Layer& ly = L[n];
  if (ly.data) return ly;
  ly.describe(n, IX.layerSize(n));
  std::string path = layerPath(DIR, n);
  int fd = open(path.c_str(), O_RDONLY);
  FileHeader h;
  if (fd < 0 || read(fd, &h, sizeof h) != sizeof h || memcmp(h.magic, "OWARELH1", 8) || h.n != n ||
      !headerSeedsMatch(h) || h.size != ly.size) {
    fprintf(stderr, "cannot use %s for a %d-seed game\n", path.c_str(), SEEDS); exit(1);
  }
  ly.mode = h.mode; ly.bytes = h.bytes;
  void* p = mmap(nullptr, sizeof h + h.bytes, PROT_READ, MAP_SHARED | MAP_POPULATE, fd, 0);
  if (p == MAP_FAILED) { perror("mmap"); exit(1); }
  close(fd);
  ly.data = static_cast<uint8_t*>(p) + sizeof h;
  return ly;
}

static double now() {
  return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();
}

// Same-layer predecessors of y (boards b with a legal, non-capturing move i such
// that play(b, i) == y), by incremental un-sowing.  Calls f(b).
template <class F>
static inline void forPredInc(const Board& y, int n, F&& f) {
  uint8_t t[PITS];  // y seen from the previous mover's side
  memcpy(t, y.p + ROW, ROW);
  memcpy(t + ROW, y.p, ROW);
  int oppTot = 0;  // previous mover's opponent row after sowing (= y's mover row)
  for (int j = ROW; j < PITS; ++j) oppTot += t[j];
  for (int i = 0; i < ROW; ++i) {
    if (t[i]) continue;  // the sown pit is empty afterwards
    Board b;
    memcpy(b.p, t, PITS);
    int oppSum = oppTot;  // opponent row of the parent before the move
    int zeros = 0;        // empty pits in the parent's opponent row
    for (int j = ROW; j < PITS; ++j) zeros += b.p[j] == 0;
    int pos = i;
    for (int s = 1; s <= n; ++s) {
      pos = pos == PITS - 1 ? 0 : pos + 1;
      if (pos == i) pos = pos == PITS - 1 ? 0 : pos + 1;
      if (b.p[pos] == 0) break;  // demands only grow with s
      --b.p[pos];
      if (pos >= ROW) { --oppSum; zeros += b.p[pos] == 0; }
      b.p[i] = uint8_t(s);
      if (!zeros) continue;                         // parent not an indexed position
      if (oppSum == 0 && s <= ROW - 1 - i) continue;  // feeding rule: must reach the opponent
      if (pos >= ROW && (t[pos] == 2 || t[pos] == 3)) {  // would this move have captured?
        int j = pos, cap = 0;
        while (j >= ROW && (t[j] == 2 || t[j] == 3)) cap += t[j--];
        if (cap != oppTot) continue;  // a real capture: child is in a lower layer
      }
      f(b);
    }
  }
}

// Reference generator from solve.cpp (for --check).
template <class F>
static inline void forPredRef(const Board& y, int n, F&& f) {
  uint8_t t[PITS];
  memcpy(t, y.p + ROW, ROW);
  memcpy(t + ROW, y.p, ROW);
  for (int i = 0; i < ROW; ++i) {
    if (t[i]) continue;
    Board b;
    for (int s = 1; s <= n; ++s) {
      int laps = s / (PITS - 1), rem = s % (PITS - 1);
      bool ok = true;
      for (int d = 1; d < PITS; ++d) {
        int j = i + d; if (j >= PITS) j -= PITS;
        int take = laps + (d <= rem);
        if (t[j] < take) { ok = false; break; }
        b.p[j] = uint8_t(t[j] - take);
      }
      if (!ok) break;
      b.p[i] = uint8_t(s);
      bool zero = false;
      for (int j = ROW; j < PITS; ++j) zero |= b.p[j] == 0;
      if (!zero) continue;
      if (!(legalMask(b) >> i & 1)) continue;
      Board chk;
      if (play(b, i, chk) != 0 || memcmp(chk.p, y.p, PITS) != 0) continue;
      f(b);
    }
  }
}

// Two-level bitmap: a summary bit per 64 words (4096 boards) so that clearing
// and scanning touch only the blocks that were used.
struct Bitmap {
  std::vector<std::atomic<uint64_t>> w, sum;
  uint64_t size;
  explicit Bitmap(uint64_t n) : w((n + 63) / 64), sum(((n + 63) / 64 + 63) / 64), size(n) {
    for (auto& x : w) x.store(0, std::memory_order_relaxed);
    for (auto& x : sum) x.store(0, std::memory_order_relaxed);
  }
  void clear() {
    for (uint64_t sw = 0; sw < sum.size(); ++sw) {
      uint64_t bits = sum[sw].exchange(0, std::memory_order_relaxed);
      while (bits) { int b = __builtin_ctzll(bits); bits &= bits - 1; w[sw * 64 + b].store(0, std::memory_order_relaxed); }
    }
  }
  bool get(uint64_t i) const { return w[i >> 6].load(std::memory_order_relaxed) >> (i & 63) & 1; }
  bool set(uint64_t i) {  // returns true if newly set
    uint64_t wd = i >> 6;
    uint64_t old = w[wd].fetch_or(1ull << (i & 63), std::memory_order_relaxed);
    if (!old) sum[wd >> 6].fetch_or(1ull << (wd & 63), std::memory_order_relaxed);
    return !(old >> (i & 63) & 1);
  }
  bool any() const { for (auto& x : sum) if (x.load(std::memory_order_relaxed)) return true; return false; }
  // Visit the used words: f(word index, word value).
  template <class F> void forWords(uint64_t swA, uint64_t swE, F&& f) const {
    for (uint64_t sw = swA; sw < swE; ++sw) {
      uint64_t bits = sum[sw].load(std::memory_order_relaxed);
      while (bits) { int b = __builtin_ctzll(bits); bits &= bits - 1; uint64_t wd = sw * 64 + b; f(wd, w[wd].load(std::memory_order_relaxed)); }
    }
  }
};

template <class F>
static void parallelFor(uint64_t n, uint64_t chunk, F&& f) {
  std::atomic<uint64_t> next{0};
  std::vector<std::thread> th;
  for (int t = 0; t < THREADS; ++t) th.emplace_back([&]() {
    for (;;) {
      uint64_t a = next.fetch_add(chunk);
      if (a >= n) return;
      f(a, std::min(a + chunk, n));
    }
  });
  for (auto& t : th) t.join();
}

int main(int argc, char** argv) {
  if (argc < 4) { fprintf(stderr, "usage: layerfix <lhdir> <seeds> <n> [threads] [check]\n"); return 1; }
  DIR = argv[1];
  SEEDS = atoi(argv[2]);
  int n = atoi(argv[3]);
  if (argc > 4) THREADS = atoi(argv[4]);
  bool check = argc > 5 && atoi(argv[5]);
  Layer ly;  // layer n parameters (clamp)
  ly.describe(n, IX.layerSize(n));
  const uint64_t size = ly.size;
  const int V = ly.V;
  double t0 = now();
  for (int m = 0; m < n; ++m) if (m != SEEDS - 1) lh(m);
  printf("layer %d: %" PRIu64 " boards, V=%d; lower layers mapped in %.1fs\n", n, size, V, now() - t0);

  if (check) {  // incremental vs reference predecessor generation on sampled boards
    uint64_t bad = 0;
    for (uint64_t i = 0; i < size; i += std::max<uint64_t>(1, size / 200000)) {
      Board y = IX.unrank(i, n);
      std::vector<uint64_t> a, b;
      forPredInc(y, n, [&](const Board& p) { a.push_back(IX.rank(p, n)); });
      forPredRef(y, n, [&](const Board& p) { b.push_back(IX.rank(p, n)); });
      std::sort(a.begin(), a.end()); std::sort(b.begin(), b.end());
      if (a != b) ++bad;
    }
    printf("predecessor check: %" PRIu64 " mismatching boards\n", bad);
    if (bad) return 1;
  }

  // Pass A: captures and non-capturing move counts.
  std::vector<uint8_t> capM(size), capN(size), mcnt(size);
  double tA = now();
  parallelFor(size, 1 << 16, [&](uint64_t a, uint64_t e) {
    for (uint64_t x = a; x < e; ++x) {
      Board b = IX.unrank(x, n);
      int mask = legalMask(b);
      if (!mask) { capM[x] = uint8_t(ly.clampCode(b.rowSum(0))); capN[x] = uint8_t(ly.clampCode(b.rowSum(ROW))); mcnt[x] = 0; continue; }
      int M = 0, N = V - 1, cnt = 0;
      Board c;
      for (int i = 0; i < ROW; ++i) if (mask >> i & 1) {
        int cap = play(b, i, c);
        if (!cap) { ++cnt; continue; }
        const Layer& lc = L[n - cap];
        int p = lc.get(IX.rank(c, n - cap));
        M = std::max(M, ly.clampCode(cap + lc.gN(p)));
        N = std::min(N, ly.clampCode(lc.gM(p)));
      }
      capM[x] = uint8_t(M); capN[x] = uint8_t(N); mcnt[x] = uint8_t(cnt);
    }
  });
  printf("pass A (captures, move counts): %.1fs\n", now() - tA);

  // Pass B: thresholds from high to low with counters carried over, so every
  // board enters W (at t = its gM code) and N (at t = its gN code) exactly once.
  std::vector<std::atomic<uint8_t>> gM(size), gN(size), counter(size);
  Bitmap FW(size), FN(size), NW(size), NN(size);
  double tB = now();
  parallelFor(size, 1 << 16, [&](uint64_t a, uint64_t e) {
    for (uint64_t x = a; x < e; ++x) {
      counter[x].store(mcnt[x], std::memory_order_relaxed);
      gM[x].store(0, std::memory_order_relaxed); gN[x].store(0, std::memory_order_relaxed);
    }
  });
  uint64_t visitsW = 0, visitsN = 0;
  for (int t = V - 1; t >= 1; --t) {
    double tt = now();
    FW.clear(); FN.clear();
    parallelFor(size, 1 << 16, [&](uint64_t a, uint64_t e) {
      for (uint64_t x = a; x < e; ++x) {
        if (capM[x] == t && gM[x].load(std::memory_order_relaxed) == 0) { gM[x].store(uint8_t(t), std::memory_order_relaxed); FW.set(x); }
        if (capN[x] >= t && counter[x].load(std::memory_order_relaxed) == 0 && gN[x].load(std::memory_order_relaxed) == 0) {
          gN[x].store(uint8_t(t), std::memory_order_relaxed); FN.set(x);
        }
      }
    });
    int gen = 0;
    uint64_t vw = 0, vn = 0;
    for (;; ++gen) {
      NW.clear(); NN.clear();
      std::atomic<uint64_t> cw{0}, cn{0};
      parallelFor(FW.sum.size(), 16, [&](uint64_t a, uint64_t e) {
        uint64_t lw = 0, ln = 0;
        FW.forWords(a, e, [&](uint64_t wd, uint64_t fw) {
          while (fw) {  // y entered W: predecessors' counters drop; zero and alive -> N
            int bit = __builtin_ctzll(fw); fw &= fw - 1; ++lw;
            Board y = IX.unrank(wd * 64 + bit, n);
            forPredInc(y, n, [&](const Board& p) {
              uint64_t r = IX.rank(p, n);
              if (counter[r].fetch_sub(1, std::memory_order_relaxed) == 1 && capN[r] >= t) {
                gN[r].store(uint8_t(t), std::memory_order_relaxed); NN.set(r);
              }
            });
          }
        });
        FN.forWords(a, e, [&](uint64_t wd, uint64_t fn) {
          while (fn) {  // y entered N: predecessors enter W
            int bit = __builtin_ctzll(fn); fn &= fn - 1; ++ln;
            Board y = IX.unrank(wd * 64 + bit, n);
            forPredInc(y, n, [&](const Board& p) {
              uint64_t r = IX.rank(p, n);
              uint8_t z = 0;
              if (gM[r].compare_exchange_strong(z, uint8_t(t), std::memory_order_relaxed)) NW.set(r);
            });
          }
        });
        cw.fetch_add(lw); cn.fetch_add(ln);
      });
      vw += cw.load(); vn += cn.load();
      if (!NW.any() && !NN.any()) break;
      std::swap(FW.w, NW.w); std::swap(FW.sum, NW.sum); std::swap(FN.w, NN.w); std::swap(FN.sum, NN.sum);
    }
    visitsW += vw; visitsN += vn;
    printf("  t=%2d: entered W %" PRIu64 ", entered N %" PRIu64 ", generations %d (%.1fs)\n", t, vw, vn, gen, now() - tt);
    fflush(stdout);
  }
  printf("pass B (thresholds): %.1fs, %" PRIu64 " W visits + %" PRIu64 " N visits; total solve %.1fs\n",
         now() - tB, visitsW, visitsN, now() - tA);

  // compare with the stored layer
  const Layer& ref = lh(n);
  std::atomic<uint64_t> badM{0}, badN{0};
  parallelFor(size, 1 << 16, [&](uint64_t a, uint64_t e) {
    uint64_t bm = 0, bn = 0;
    for (uint64_t x = a; x < e; ++x) { int p = ref.get(x); bm += ref.decM[p] != gM[x].load(std::memory_order_relaxed); bn += ref.decN[p] != gN[x].load(std::memory_order_relaxed); }
    badM.fetch_add(bm); badN.fetch_add(bn);
  });
  printf("layer %d: compared with stored layer: gM mismatches %" PRIu64 ", gN mismatches %" PRIu64 "%s\n",
         n, badM.load(), badN.load(), badM.load() + badN.load() ? "  FAILED" : "  OK");
  return badM.load() + badN.load() ? 1 : 0;
}
