// Oware 6x2 strong solver: layered retrograde analysis over the number of seeds on
// the board, producing per-board sound guarantees (see layer.hpp) from which the
// win/draw/loss value of every (board, scores, side to move) state follows.
//
//   solve <outdir> [seeds=48] [threads=all] [maxN=seeds]
//
// seeds is the total number of seeds in the game (4 per pit = 48 for standard Oware,
// 3 per pit = 36, ...); the rules are otherwise unchanged and seeds/2+1 captures win.
//
// Layers are solved in increasing n; a capture leads to a strictly smaller layer, so
// each layer only needs the finished smaller ones plus a fixpoint inside the layer.
// Inside a layer the least fixpoint of
//     gM(b) = max over moves  (cap + gN(child))      gN(b) = min over moves gM(child)
// is reached by chaotic iteration driven by a dirty bitmap: when a board's value
// rises, its same-layer predecessors (generated by un-sowing) are marked dirty.
// A final full pass re-evaluates every board and checks that the result is a
// fixpoint; values only ever rise from 0, so a fixpoint reached this way is the least
// one.  The pass also gathers statistics and converts the layer to its final packing.
#include <omp.h>
#include <sys/stat.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cinttypes>
#include "layer.hpp"
#include "oware.hpp"
using namespace oware;

static Index IX;
static Layer L[MAX_SEEDS + 1];
static std::string outDir;
static const uint64_t BLOCK_WORDS = 3 * 1024;  // 196,608 boards; divisible by 2, 3, 8

static double now() {
  return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();
}

// Evaluate board b of layer n from its successors: codes (eM, eN).
static inline void evaluate(const Board& b, int n, const Layer& ly, int& eM, int& eN) {
  int mask = legalMask(b);
  if (!mask) {  // no legal move: remaining seeds go to the owners of their pits
    eM = ly.clampCode(b.rowSum(0));
    eN = ly.clampCode(b.rowSum(ROW));
    return;
  }
  int M = 0, N = ly.V - 1;
  Board c;
  for (int i = 0; i < ROW; ++i) {
    if (!(mask >> i & 1)) continue;
    int cap = play(b, i, c);
    if (cap) {
      const Layer& lc = L[n - cap];
      int p = lc.get(IX.rank(c, n - cap));
      M = std::max(M, ly.clampCode(cap + lc.gN(p)));
      N = std::min(N, ly.clampCode(lc.gM(p)));
    } else {
      int p = ly.get(IX.rank(c, n));
      M = std::max<int>(M, ly.decN[p]);
      N = std::min<int>(N, ly.decM[p]);
    }
  }
  eM = M; eN = N;
}

// Same-layer predecessors of board y: boards b and pits i with play(b,i) == y and no
// capture.  Calls f(index of b).
template <class F>
static inline void forPredecessors(const Board& y, int n, F&& f) {
  uint8_t t[PITS];  // y seen from the previous mover's side
  memcpy(t, y.p + ROW, ROW);
  memcpy(t + ROW, y.p, ROW);
  for (int i = 0; i < ROW; ++i) {
    if (t[i]) continue;
    Board b;
    for (int s = 1; s <= n; ++s) {
      int laps = s / 11, rem = s % 11;
      bool ok = true;
      for (int d = 1; d < PITS; ++d) {
        int j = i + d; if (j >= PITS) j -= PITS;
        int take = laps + (d <= rem);
        if (t[j] < take) { ok = false; break; }
        b.p[j] = uint8_t(t[j] - take);
      }
      if (!ok) break;  // demands only grow with s
      b.p[i] = uint8_t(s);
      bool zero = false;
      for (int j = ROW; j < PITS; ++j) zero |= b.p[j] == 0;
      if (!zero) continue;  // not an indexed position
      if (!(legalMask(b) >> i & 1)) continue;
      Board chk;
      if (play(b, i, chk) != 0 || memcmp(chk.p, y.p, PITS) != 0) continue;
      f(IX.rank(b, n));
    }
  }
}

static bool loadLayer(int n) {
  std::string path = layerPath(outDir, n);
  FILE* fp = fopen(path.c_str(), "rb");
  if (!fp) return false;
  FileHeader h;
  Layer& ly = L[n];
  bool ok = fread(&h, sizeof h, 1, fp) == 1 && !memcmp(h.magic, "OWARELH1", 8) && h.n == n &&
            headerSeedsMatch(h) && h.size == ly.size && h.P == ly.P && h.mode == ly.finalMode();
  if (ok) {
    ly.alloc(h.mode);
    ok = h.bytes == ly.bytes;
    uint64_t done = 0;
    while (ok && done < ly.bytes) {
      size_t r = fread(ly.data + done, 1, std::min<uint64_t>(ly.bytes - done, 1ull << 30), fp);
      if (!r) ok = false;
      done += r;
    }
    if (!ok) ly.release();
  }
  fclose(fp);
  return ok;
}

static void saveLayer(int n) {
  Layer& ly = L[n];
  std::string path = layerPath(outDir, n), tmp = path + ".tmp";
  FILE* fp = fopen(tmp.c_str(), "wb");
  if (!fp) { perror(tmp.c_str()); exit(1); }
  FileHeader h{};
  memcpy(h.magic, "OWARELH1", 8);
  h.n = n; h.A = ly.A; h.V = ly.V; h.P = ly.P; h.mode = ly.mode; h.G = ly.G; h.w = ly.w;
  h.seeds = SEEDS; h.size = ly.size; h.bytes = ly.bytes;
  bool ok = fwrite(&h, sizeof h, 1, fp) == 1;
  for (uint64_t done = 0; ok && done < ly.bytes;) {
    uint64_t chunk = std::min<uint64_t>(ly.bytes - done, 1ull << 30);
    ok = fwrite(ly.data + done, 1, chunk, fp) == chunk;
    done += chunk;
  }
  if (fclose(fp) != 0 || !ok) { fprintf(stderr, "write failed: %s\n", tmp.c_str()); exit(1); }
  rename(tmp.c_str(), path.c_str());
}

static void solveLayer(int n) {
  Layer& ly = L[n];
  const uint64_t size = ly.size;
  double t0 = now();
  ly.alloc(ly.workMode());
  const uint64_t words = (size + 63) / 64;
  const uint64_t blocks = (words + BLOCK_WORDS - 1) / BLOCK_WORDS;
  auto* dirty = static_cast<std::atomic<uint64_t>*>(
      mmap(nullptr, words * 8 + 8, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_NORESERVE, -1, 0));
  madvise(dirty, words * 8, MADV_HUGEPAGE);

  auto setAllDirty = [&] {
    #pragma omp parallel for schedule(static)
    for (uint64_t wd = 0; wd < words; ++wd) {
      uint64_t left = size - wd * 64;
      dirty[wd].store(left >= 64 ? ~0ull : (1ull << left) - 1, std::memory_order_relaxed);
    }
  };

  // Sweep 0 seeds every board from terminals, captures and whatever is already known
  // in the layer, without predecessor marking; afterwards everything is dirty once
  // more and later sweeps propagate changes only.
  setAllDirty();
  for (int sweep = 0;; ++sweep) {
    uint64_t processed = 0, changed = 0;
    double ts = now();
    #pragma omp parallel for schedule(dynamic, 1) reduction(+ : processed, changed)
    for (uint64_t blk = 0; blk < blocks; ++blk) {
      uint64_t w1 = std::min(words, (blk + 1) * BLOCK_WORDS);
      for (uint64_t wd = blk * BLOCK_WORDS; wd < w1; ++wd) {
        if (!dirty[wd].load(std::memory_order_relaxed)) continue;
        uint64_t bits = dirty[wd].exchange(0);
        while (bits) {
          uint64_t x = wd * 64 + __builtin_ctzll(bits);
          bits &= bits - 1;
          ++processed;
          int p = ly.get(x);
          if (ly.decM[p] + ly.decN[p] == ly.V - 1) continue;  // already exact
          Board b = IX.unrank(x, n);
          int eM, eN;
          evaluate(b, n, ly, eM, eN);
          eM = std::max<int>(eM, ly.decM[p]);
          eN = std::max<int>(eN, ly.decN[p]);
          int q = ly.enc[eM][eN];
          if (q == p) continue;
          if (q == 0xffff) { fprintf(stderr, "inconsistent guarantees n=%d x=%" PRIu64 "\n", n, x); exit(2); }
          ly.set(x, p, q);
          ++changed;
          if (sweep > 0)
            forPredecessors(b, n, [&](uint64_t pi) {
              dirty[pi >> 6].fetch_or(1ull << (pi & 63));
            });
        }
      }
    }
    if (sweep == 0) setAllDirty();
    if (sweep < 3 || sweep % 10 == 0 || !processed)
      printf("  n=%d sweep %d: processed %" PRIu64 " changed %" PRIu64 " (%.1fs)\n", n, sweep, processed, changed, now() - ts);
    fflush(stdout);
    if (sweep > 0 && !processed) break;
  }
  munmap(dirty, words * 8 + 8);
  double t1 = now();

  // Verification + statistics + final packing.
  Layer fin = ly;
  bool convert = ly.finalMode() != ly.mode;
  if (convert) fin.alloc(ly.finalMode());
  std::vector<uint64_t> hist(ly.P, 0);
  uint64_t bad = 0;
  const uint64_t groups = (size + 7) / 8;
  #pragma omp parallel
  {
    std::vector<uint64_t> h(ly.P, 0);
    uint64_t myBad = 0;
    #pragma omp for schedule(dynamic, 1 << 14)
    for (uint64_t g = 0; g < groups; ++g) {
      uint64_t acc = 0;
      for (uint64_t x = g * 8; x < std::min(size, g * 8 + 8); ++x) {
        int p = ly.get(x);
        ++h[p];
        if (ly.decM[p] + ly.decN[p] != ly.V - 1) {
          int eM, eN;
          evaluate(IX.unrank(x, n), n, ly, eM, eN);
          if (eM != ly.decM[p] || eN != ly.decN[p]) ++myBad;
        } else if ((x & 1023) == 0) {  // spot-check exact entries too
          int eM, eN;
          evaluate(IX.unrank(x, n), n, ly, eM, eN);
          if (eM != ly.decM[p] || eN != ly.decN[p]) ++myBad;
        }
        acc |= uint64_t(p) << ((x & 7) * ly.w);
      }
      if (convert) memcpy(fin.data + g * ly.w, &acc, ly.w);
    }
    #pragma omp critical
    { for (int p = 0; p < ly.P; ++p) hist[p] += h[p]; bad += myBad; }
  }
  if (bad) { fprintf(stderr, "n=%d: %" PRIu64 " boards are not at a fixpoint\n", n, bad); exit(3); }
  if (convert) { ly.release(); ly = fin; }
  saveLayer(n);

  // Statistics: exact boards, and W/D/L per score split.
  uint64_t exact = 0;
  for (int p = 0; p < ly.P; ++p) if (ly.decM[p] + ly.decN[p] == ly.V - 1) exact += hist[p];
  std::string sp = outDir + "/stats.txt";
  FILE* fs = fopen(sp.c_str(), "a");
  fprintf(fs, "layer %d size %" PRIu64 " exact %" PRIu64 " solve_s %.1f verify_s %.1f\n", n, size, exact, t1 - t0, now() - t1);
  const int win = winSeeds(), half = win - 1;
  int cmin = std::max(0, half - n), cmax = std::min(half, SEEDS - n);
  for (int c = cmin; c <= cmax; ++c) {  // c = seeds already captured by the side to move
    int c2 = SEEDS - n - c;
    uint64_t W = 0, Lo = 0, Dx = 0, Dc = 0;
    for (int p = 0; p < ly.P; ++p) {
      int gm = ly.gM(p), gn = ly.gN(p);
      if (c + gm >= win) W += hist[p];
      else if (c2 + gn >= win) Lo += hist[p];
      else if (c + gm == half && c2 + gn == half) Dx += hist[p];
      else Dc += hist[p];
    }
    fprintf(fs, "  n %d mover_captured %d other_captured %d win %" PRIu64 " loss %" PRIu64 " draw_forced %" PRIu64 " draw_cycle %" PRIu64 "\n",
            n, c, c2, W, Lo, Dx, Dc);
  }
  fclose(fs);
  printf("layer %2d: size %" PRIu64 " exact %.3f%% solve %.1fs verify %.1fs\n", n, size, 100.0 * exact / std::max<uint64_t>(size, 1), t1 - t0, now() - t1);
  fflush(stdout);
}

int main(int argc, char** argv) {
  if (argc < 2) { fprintf(stderr, "usage: solve <outdir> [seeds=48] [threads=all] [maxN=seeds]\n"); return 1; }
  outDir = argv[1];
  SEEDS = argc > 2 ? atoi(argv[2]) : MAX_SEEDS;
  if (SEEDS < 2 || SEEDS > MAX_SEEDS || SEEDS % 2) {
    fprintf(stderr, "seeds must be even and between 2 and %d\n", MAX_SEEDS); return 1;
  }
  if (argc > 3 && atoi(argv[3]) > 0) omp_set_num_threads(atoi(argv[3]));
  int maxN = argc > 4 ? std::min(atoi(argv[4]), SEEDS) : SEEDS;
  const int win = winSeeds();
  printf("solving %d-seed Oware (%d captured seeds win) into %s\n", SEEDS, win, outDir.c_str());
  mkdir(outDir.c_str(), 0775);
  for (int n = 0; n <= maxN; ++n) {
    if (n == SEEDS - 1) continue;  // a single seed can never be captured
    L[n].describe(n, IX.layerSize(n));
    if (loadLayer(n)) { printf("layer %2d: loaded\n", n); fflush(stdout); continue; }
    solveLayer(n);
  }
  if (maxN == SEEDS && SEEDS % PITS == 0) {
    Board init, c;
    memset(init.p, SEEDS / PITS, PITS);
    int M = 0, N = 99;
    for (int i = 0; i < ROW; ++i) {
      int cap = play(init, i, c);  // the first move can capture with 1 or 2 seeds per pit
      const Layer& lc = L[SEEDS - cap];
      int p = lc.get(IX.rank(c, SEEDS - cap));
      M = std::max(M, cap + lc.gN(p)); N = std::min(N, lc.gM(p));
    }
    char v[64];
    if (M >= win) snprintf(v, sizeof v, "FIRST-PLAYER WIN");
    else if (N >= win) snprintf(v, sizeof v, "SECOND-PLAYER WIN");
    else if (M == win - 1 && N == win - 1) snprintf(v, sizeof v, "DRAW (forced %d-%d)", win - 1, win - 1);
    else snprintf(v, sizeof v, "DRAW (no forced win)");
    printf("initial position: first player forces >= %d%s, second player forces >= %d%s: %s\n",
           M, M < win - 1 ? " (or fewer)" : "", N, N < win - 1 ? " (or fewer)" : "", v);
  }
  return 0;
}
